apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    teams: intergration
    app: todo
spec:
  containers:
    - name: nginx-container 
      image: nginx:latest
      ports:
        - containerPort: 80

    